version: '3.6'
services:
  iris:
    init: true
    image: intersystemscommunity/pexdemo:latest
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - 'jgw'
#      - 'netgw'
    ports:
      - 9980:9980
      - 42773:52773
      - 41773:51773
      - 55555:55555
volumes:
      - /efs/ICS/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
      - /efs/ICS:/ICS
